name: Device Client - .NET Build

on:
  push:
    branches: 
      - main
      - 'version/**' 
    # Only trigger if changes to Device Client has been made
    paths: 
      - 'DeviceClient/AbeckDev.DoorController.DeviceClient/**'
  pull_request:
    branches: 
      - main
      - 'version/**' 
    # Only trigger if changes to Device Client has been made
    paths: 
      - 'DeviceClient/AbeckDev.DoorController.DeviceClient/**'
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET 
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.407
    - name: Debug pwd
      run: pwd
    - name: Directory Content
      run: ls
    - name: Install dependencies
      working-directory: DeviceClient/AbeckDev.DoorController.DeviceClient/AbeckDev.DoorController.DeviceClient/
      run: dotnet restore
    - name: Build
      working-directory: DeviceClient/AbeckDev.DoorController.DeviceClient/AbeckDev.DoorController.DeviceClient/
      run: dotnet build --configuration Release --no-restore
    - name: dotnet publish
      run: mkdir -p /home/runner/work/IoTDoorController/publish; dotnet publish -c Release -o /home/runner/work/IoTDoorController/publish
      working-directory: DeviceClient/AbeckDev.DoorController.DeviceClient/AbeckDev.DoorController.DeviceClient/
    - name: Build Drop Archive
      run: zip /home/runner/work/IoTDoorController/drop.zip -r /home/runner/work/IoTDoorController/publish/*
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2
      with:
        # Artifact name
        name: DoorController-Release
        # A file, directory or wildcard pattern that describes what to upload
        path: /home/runner/work/IoTDoorController/publish/
    
